### PR TITLE
Add favorites toggle

### PR DESCRIPTION
**Pull request by cmpaul**
Thought this might be useful! Adds a toggle and sorts favorites to the top.

faves

### CODE REVIEW

**Comment by braver** [comment]
Neat!

Props for using local storage. Perhaps we should move the other settings away from cookies as well for some proper data storage.

You seem to have broken the regular clicks on the list entries though. The ❤️ icon should be a separate button element that adds/removes the font from the favorites. I'd also prefer to use the pin/unpin metaphor here with this icon: https://octicons.github.com/icon/pin/

**Comment by cmpaul** [comment]
@braver You got it!

**Comment by cmpaul** [comment]
@braver Let me know what you think.

image

**Comment by braver** [comment]
Super cool, thanks! I’ll do a final check and spit-n-polish tomorrow. 🍻

**Pull request merged**
