### PR TITLE
Envy Code R, Preview 7

### PR DESCRIPTION
**Pull request by BourgeoisBear**

### CODE REVIEW

**Comment by braver** [comment]
Ah, now I remember why it’s not on the site:

> Free to use but redistribution prohibited.

I should get in touch with the author, see if it’s ok to put it on the site in woff format.

**Comment by BourgeoisBear** [comment]
@braver Good deal!

**Comment by braver** [comment]
Ok, it's good and approved. Did you do the woff conversion yourself?

**Comment by BourgeoisBear** [comment]
Probably.  Not sure though.  If I did, I used the `woff-tools` package in the Debian repos.

**Comment by braver** [comment]
I got originals from the author, so I’m going to use those. 👌🏻

**Pull request closed without merging**
