### PR TITLE
Update Victor Mono + search in author, description and year as well

### PR DESCRIPTION
**Pull request by rubjo**

### CODE REVIEW

**Comment by rubjo** [comment]
Hi good @braver :) Hope life is treating you well. Here are a couple of changes you can consider. :)

**Comment by braver** [comment]
Oh, that's smart. I wonder if searching in the description would give too many false positives, especially since it's not visible in the listing panel.

**Comment by rubjo** [comment]
That’s a good point, feel free to remove that line 🙂

**Comment by waldyrious** [comment]
I can see why someone might search a font by its author (I find it unlinkely that they'd know the author but not the name, but still, seems plausible). But are people actually searching for fonts by _year_? :thinking:

**Comment by rubjo** [comment]
Well, without a way to sort by year, there’s no other way to quickly see only recent fonts.

**Comment by braver** [comment]
> But are people actually searching for fonts by year?

I dunno, but I like being able to quickly see what's new this year

**Pull request merged**
