### PR TITLE
Add DM mono

### LINKED ISSUE #96: Adding dm-mono
I think this would be a great font to add https://github.com/googlefonts/dm-mono

I can make a pull request if it's as simple as updating the CSS files and converting/updating the fonts.

### PR DESCRIPTION
**Pull request by jonboiser**
This adds DM Mono (my new fave monospace font) to the list of fonts:

image

Closes #96

### CODE REVIEW

**Comment by braver** [comment]
Thanks! Looks mostly in order. Some things I spotted:

- the zero seems to be slashed, not dotted
- I'd like the font file names to also have the dash, just like the folder (dm-mono), to have a consistent alias for the font name

**Comment by jonboiser** [comment]
@braver Thanks for the feedback! I made the changes to `fonts.json` and updated the file names/CSS.

**Comment by jonboiser** [comment]
@braver Thanks for the feedback! I made the changes to `fonts.json` and updated the file names/CSS.

**Comment by braver** [comment]
Excellent!

**Pull request merged**
